
appEngine:
  projectId: domain-registry-alpha

registryPolicy:
  contactAndHostRoidSuffix: ROID
  productName: Google Registry Alpha

registrarConsole:
  logoFilename: google_registry.png

gSuite:
  # Publicly accessible domain name of the running G Suite instance.
  domainName: domain-registry.example

  # Display name and email address used on outgoing emails through G Suite.
  outgoingEmailDisplayName: Donuts Domain Registry
  outgoingEmailAddress: noreply@project-id.appspotmail.com

  # Email address of the admin account on the G Suite app. This is used for
  # logging in to perform administrative actions, not sending emails.
  adminAccountEmailAddress: admin@example.com
