package(
    default_visibility = ["//java/google/registry:registry_project"],
)

licenses(["notice"])  # Apache 2.0


java_library(
    name = "common_ear_metainf",
    resources = glob(["META-INF/*"]),
)
